from django.urls import path

from diagnostics.views import DiagnoseFixView, DiagnoseView

from .views import (
    AccountReviewView,
    ApplyView,
    AuditView,
    AuditExportView,
    ConsoleBootstrapView,
    ClientPrewireView,
    DeploymentHistoryView,
    DeploymentStatusRefreshView,
    DeployDetectView,
    DeployView,
    DiscoverView,
    GitHubImportView,
    PlanView,
    PlatformSetupAuditView,
    PlatformSetupRunView,
    ProviderStatusView,
    RollbackView,
    TerraformApplyView,
    TerraformPlanView,
    TransferStartView,
    TransferHistoryView,
    TransferMetricsView,
    TransferReplayView,
    TransferStatusView,
    TransferStopView,
    EnvInjectView,
    RailwayEnvBackupView,
)

urlpatterns = [
    path("discover", DiscoverView.as_view(), name="discover"),
    path("review", AccountReviewView.as_view(), name="account-review"),
    path("plan", PlanView.as_view(), name="plan"),
    path("apply", ApplyView.as_view(), name="apply"),
    path("rollback", RollbackView.as_view(), name="rollback"),
    path("terraform/plan", TerraformPlanView.as_view(), name="terraform-plan"),
    path("terraform/apply", TerraformApplyView.as_view(), name="terraform-apply"),
    path("deploy/detect", DeployDetectView.as_view(), name="deploy-detect"),
    path("github/import", GitHubImportView.as_view(), name="github-import"),
    path("deploy", DeployView.as_view(), name="deploy"),
    path("deploy/history", DeploymentHistoryView.as_view(), name="deploy-history"),
    path("deploy/status/<str:deployment_id>", DeploymentStatusRefreshView.as_view(), name="deploy-status-refresh"),
    path("diagnose", DiagnoseView.as_view(), name="diagnose"),
    path("diagnose/fix", DiagnoseFixView.as_view(), name="diagnose-fix"),
    path("transfer/start", TransferStartView.as_view(), name="transfer-start"),
    path("transfer/stop", TransferStopView.as_view(), name="transfer-stop"),
    path("transfer/status", TransferStatusView.as_view(), name="transfer-status"),
    path("transfer/history", TransferHistoryView.as_view(), name="transfer-history"),
    path("transfer/metrics", TransferMetricsView.as_view(), name="transfer-metrics"),
    path("transfer/replay/<str:run_id>", TransferReplayView.as_view(), name="transfer-replay"),
    path("console/bootstrap", ConsoleBootstrapView.as_view(), name="console-bootstrap"),
    path("platform/setup-audit", PlatformSetupAuditView.as_view(), name="platform-setup-audit"),
    path("platform/setup-run", PlatformSetupRunView.as_view(), name="platform-setup-run"),
    path("clients/prewire", ClientPrewireView.as_view(), name="client-prewire"),
    path("providers/status", ProviderStatusView.as_view(), name="provider-status"),
    path("audit", AuditView.as_view(), name="audit"),
    path("audit/export", AuditExportView.as_view(), name="audit-export"),
    path("env/inject", EnvInjectView.as_view(), name="env-inject"),
    path("env/backup/railway", RailwayEnvBackupView.as_view(), name="railway-env-backup"),
]
