# Generated by Django 4.2.30 on 2026-06-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('plan_slug', models.CharField(default='free', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='default_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='billing.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('operator', 'operator'), ('viewer', 'viewer')], default='viewer', max_length=32)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='billing.workspace')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('workspace', 'email')},
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='billing.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'kind', 'created_at'], name='billing_usa_workspa_826fca_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('render', 'render'), ('railway', 'railway'), ('fly', 'fly'), ('kong', 'kong'), ('terraform', 'terraform'), ('supabase', 'supabase'), ('cloudflare', 'cloudflare'), ('stripe', 'stripe')], max_length=32)),
                ('live_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(default='not_configured', max_length=32)),
                ('capabilities', models.JSONField(default=list)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='billing.workspace')),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('workspace', 'provider')},
            },
        ),
    ]
