# Generated by Django 5.0.14 on 2026-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_index=True, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=128)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('entry_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
