# Generated by Django 4.2.30 on 2026-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('app_name', models.CharField(max_length=128)),
                ('target_provider', models.CharField(max_length=32)),
                ('requested_by', models.CharField(max_length=128)),
                ('live', models.BooleanField(default=False)),
                ('succeeded', models.BooleanField(default=False)),
                ('live_url', models.URLField(blank=True, default='')),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
