# Generated by Django 4.2.30 on 2026-06-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_workspace_customer_default_workspace_workspacemember_and_more'),
        ('migrationengine', '0002_deploymentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentrun',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_runs', to='billing.workspace'),
        ),
    ]
