# Generated by Django 4.2.30 on 2026-06-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationengine', '0003_deploymentrun_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentrun',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymentrun',
            name='provider_deploy_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='deploymentrun',
            name='provider_service_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='deploymentrun',
            name='provider_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deploymentrun',
            name='status',
            field=models.CharField(default='unknown', max_length=32),
        ),
    ]
